### ISSUE TITLE
Conversion from Interval to FiniteDuration

### ISSUE THREAD

**Issue by acjay** [nscala-time/nscala-time#105]
What's the best way is to convert from an `Interval` to a `FiniteDuration` (used in the standard library)? Related to that, could there be an implicit conversion for this?

**Comment by xuwei-k** [comment]
https://github.com/nscala-time/nscala-time/blob/releases/2.10.0/src/main/scala/com/github/nscala_time/time/RichDuration.scala

```
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.github.nscala_time.time.Implicits._
import com.github.nscala_time.time.Implicits._

scala> new org.joda.time.Interval(0, 1)
res0: org.joda.time.Interval = 1970-01-01T09:00:00.000+09:00/1970-01-01T09:00:00.001+09:00

scala> res0.toDuration.toScalaDuration
res1: scala.concurrent.duration.Duration = 1 millisecond
```

**Comment by acjay** [comment]
That doesn't quite get me there, as the API I'm trying to use requires `FiniteDuration`.

Right now, I'm using `time => (DateTime.now() to time).toDurationMillis.millis`, with `import scala.concurrent.duration._` to get the unit methods. It feels like there should be a way to just drop in the interval I want where w `FiniteDuration` is expected. Would it be undesirable for this implicit conversion to exist?

**Comment by tkawachi** [comment]
`toScalaDuration` will return FiniteDuration since the next version. https://github.com/nscala-time/nscala-time/pull/106/files
Is it sufficient for you?

**Comment by acjay** [comment]
That helps out, but it would be useful to have that on `Interval` too. With `toScalaDuration`, it still looks like `time => (DateTime.now() to time).toDuration.toScalaDuration`, which seems overly verbose for what it's trying to accomplish.
