### ISSUE TITLE
max min to DateTime

### ISSUE THREAD

**Issue by gilcu2** [nscala-time/nscala-time#107]
Can you add so?

val a=DateTime()
val b=DateTime()
val c=a max b

Thanks

**Comment by kmizu** [comment]
I don't think that it's good to add such methods since what `max` and/or `min` means is not trivial.  If you would like to do so, write as the following:

```scala
a.getMillis() max b.getMillis()
```

**Comment by xuwei-k** [comment]
see https://github.com/nscala-time/nscala-time/issues/97

**Comment by gilcu2** [comment]
Thanks
