### ISSUE TITLE
Get weird result when I want to find period between two dates and subtract some date by it

### ISSUE THREAD

**Issue by DingChiLin** [nscala-time/nscala-time#119]
I have a problem, when I want to find the period between two dates, and subtract some other date by this period, I will get different answer when I choose different date. For example:

```

val t1 = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss").parseDateTime("2017-6-13 12:00:00")
val t2 = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss").parseDateTime("2017-07-30 12:00:00")
val t3 = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss").parseDateTime("2017-07-31 12:00:00")

t2 - (t1 to t2).toPeriod // 2017-06-13T12:00:00.000+08:00  It's OK, just give me the time of t1
t3 - (t1 to t3).toPeriod // 2017-06-12T12:00:00.000+08:00  It's weird !?? Why I miss one day !??
 
```

**Comment by xuwei-k** [comment]
see https://github.com/JodaOrg/joda-time/blob/v2.9.9/src/main/java/org/joda/time/DateTime.java#L1264-L1272


> This method will subtract each element of the period one by one, from largest to smallest, adjusting the datetime to be accurate between each.
>
> Thus, subtracting a period of one month and one day from 2007-05-31 will work as follows: First subtract one month and adjust, resulting in 2007-04-30 Then subtract one day and adjust, resulting in 2007-04-29. Note that the day has been adjusted by two.
