### ISSUE TITLE
Release with the latest joda

### ISSUE THREAD

**Issue by alexanderzafirov** [nscala-time/nscala-time#121]
Hello,

I'd like to know when will there be a new release of the lib? I can see that the latest joda has been added in March but no release has been made since December last year.

I use scalikejdbc and there the dependencies are for 2.9.9.

Can you please make a new release and possibly add that to maven central?

Thank you!

**Comment by xuwei-k** [comment]
- https://github.com/nscala-time/nscala-time/releases/tag/releases%2F2.18.0
- https://oss.sonatype.org/content/repositories/releases/com/github/nscala-time/nscala-time_2.12/2.18.0/
