### ISSUE TITLE
Unexpected behaviour with setting DateTime to Midnight

### ISSUE THREAD

**Issue by kkeenan02** [nscala-time/nscala-time#129]
Not sure if this is the best way to get a day date with nscala-time, but I noticed the below unexpected behaviour (very new to scala, so could be misunderstanding):

## Observed unexpected behaviour
```scala
scala> (new DateTime)
  .withYear(2018)
  .withMonth(11)
  .withDay(20)
  .withHour(0)
  .withMinute(0)
  .withSecond(0)
  .withMillis(0)
res39: org.joda.time.DateTime = 1970-01-01T00:00:00.000Z
```

## Expected the following result

```scala
org.joda.time.DateTime = 2018-11-20T00:00:00.000Z
```

**Comment by kkeenan02** [comment]
I just discovered the .toDateMidnight method, which is probabably the correct way to achieve what I want, however, millis is not 0 in this result, so I'm guessing the above behaviour is a result of trying to set milliseconds to 0

**Comment by xuwei-k** [comment]
I think this is not nscala-time bug. closing
