### ISSUE TITLE
conflict of implicits with scala.concurrent.duration

### ISSUE THREAD

**Issue by newffy** [nscala-time/nscala-time#36]
import scala.concurrent.duration._
import com.github.nscala_time.time.Imports._

val timeoutx = 5.seconds

leads to 
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method DurationInt in package duration of type (n: Int)scala.concurrent.duration.package.DurationInt
[error]  and method RichInt in trait IntImplicits of type (n: Int)com.github.nscala_time.time.RichInt
[error]  are possible conversion functions from Int(5) to ?{def seconds: ?}
[error]       val timeoutx = 5.seconds

**Comment by webgress** [comment]
Here is what I did to solve this type of problem locally:

**Comment by rafalsobota** [comment]
@webgress nice
Can it be added to com.github.nscala_time.time.Imports?

**Comment by rishmehta** [comment]
cool
