### ISSUE TITLE
Java 8 date and time API support

### ISSUE THREAD

**Issue by Groggy** [nscala-time/nscala-time#85]
It could be nice to support Java 8 date and time API which is pretty much a copy of Joda Time.

This also means no external dependencies.

**Comment by MadMartian** [comment]
Hear, hear!

**Comment by kmizu** [comment]
> It could be nice to support Java 8 date and time API which is pretty much a copy of Joda Time.
Although I have not so much time, I agree.  Pull requests are welcome!

**Comment by xuwei-k** [comment]
nscala-time is just a wrapper of joda-time. 
I think it should be different name and repository if create Java 8 date time API wrapper library.

**Comment by kmizu** [comment]
Sorry!I I forgot to reply.  After rethinking,  I agree @xuwei-k 's opinion.  Java 8 date and time API wrapper project should be separated from nscala-time.

**Comment by xuwei-k** [comment]
FYI there is a JSR-310 scala wrapper https://github.com/reactivecodes/scala-time

**Comment by xuwei-k** [comment]
see also https://github.com/opt-tech/chronoscala
