### ISSUE TITLE
When will the next version come out?

### ISSUE THREAD

**Issue by pishen** [nscala-time/nscala-time#87]
We need the fix of #83 here. Can only get it from 1.9.0-SNAPSHOT now. Hope the next stable version could come out soon.

**Comment by kmizu** [comment]
Hi, @pishen I'm sorry for the late release of the next version.  I'll plan to release 2.0.0 tomorrow. Is it OK ?

**Comment by pishen** [comment]
Of course, thanks for the great work. :D

**Comment by kmizu** [comment]
Hi, @pishen.  I've published [nscala-time 2.0.0](https://oss.sonatype.org/content/repositories/releases/com/github/nscala-time/nscala-time_2.11/2.0.0/) today.  See release note: https://github.com/nscala-time/nscala-time/blob/master/README.md
