### ISSUE TITLE
New released needed for JDK 1.8u60

### ISSUE THREAD

**Issue by mslinn** [nscala-time/nscala-time#94]
The current version of `nscala-time` is incompatible with JDK 1.8u60. [AWS Java SDK - AWS authentication requires a valid Date or x-amz-date header](http://stackoverflow.com/questions/32058431/aws-java-sdk-aws-authentication-requires-a-valid-date-or-x-amz-date-header)

I see HEAD has updated the `joda-time` dependency but that version has not been released yet. It would be great if `nscala-time` updates for Scala 2.10 & 2.11 of could be released soon.

**Comment by xuwei-k** [comment]
released 2.2.0

- https://github.com/nscala-time/nscala-time/tree/releases/2.2.0
- https://oss.sonatype.org/content/repositories/releases/com/github/nscala-time/nscala-time_2.11/2.2.0/

**Comment by mslinn** [comment]
Please release a Scala 2.10 version also!
